# Adaptation of colors from WezTerm to Alacritty in TOML format

# [[colors.indexed_colors]]
# color = "#ffa066" # Additional color
# index = 16
#
# [[colors.indexed_colors]]
# color = "#ff5d62" # Additional color
# index = 17
#

[colors.bright]
black = "#24283b"
blue = "#a3c5ff"
cyan = "#b4f9f8"
green = "#e0ffad"
magenta = "#bb9af7"
red = "#c53b53"
white = "#d1e5ed"
yellow = "#ffee7e"

[colors.normal]
black = "#181a29"
blue = "#93bbff"
cyan = "#98e4ff"
green = "#c3e88d"
magenta = "#bb9af7"
red = "#c53b53"
white = "#bfd5de"
yellow = "#ff9e64"

[colors.primary]
background = "#1f2335"
foreground = "#ffffff"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 14

[font.normal]
family = "Iosevka Term"

[window]
opacity = 0.96

[env]
TERM = "xterm-256color"

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"
