[[colors.indexed_colors]]
color = "#ffa066"
index = 16

[[colors.indexed_colors]]
color = "#ff5d62"
index = 17

[colors.bright]
black = "#24283b"
blue = "#a3c5ff"
cyan = "#b4f9f8"
green = "#e0ffad"
magenta = "#bb9af7"
red = "#c53b53"
white = "#d1e5ed"
yellow = "#ffee7e"

[colors.normal]
black = "#181a29"
blue = "#93bbff"
cyan = "#98e4ff"
green = "#c3e88d"
magenta = "#bb9af7"
red = "#c53b53"
white = "#bfd5de"
yellow = "#ff9e64"

[colors.cursor]

[cursor]
style = "Block"
unfocused_hollow = true

[colors.primary]
background = "#0f101a"
foreground = "#c5c9de"

[window]
opacity = 0.9

[font]
size = 16

[font.normal]
family = "UbuntuMono Nerd Font"

[shell]
program = "/usr/bin/fish"
